### ISSUE TITLE
Downloader generates wrong tests.

### ISSUE THREAD

**Issue by mamogaaa** [kaikash/yandex-contest-manager#1]
Example: `abcdefghijklmnopqrstuvwxyz&lt;ESC&gt;`
Possible solution: use innerText instead of innerHTML.

**Comment by kaikash** [comment]
Fixed in [5866b7b](https://github.com/kaikash/yandex-contest-manager/commit/1dd58f1f08a5bd722bd4beaf993a85f9be35eb7c)
